#include "GfxModule.hh"

#include <utility>
#include "../Core.hh"
#include "../Debug/Log.hh"
#include "../Data/ResourceLoader.hh"
#include "../Visual/Window.hh"

#include <flextGL.h>
#include "GL33/GBuffer.hh"

namespace Ares
{

struct GfxModule::RenderData
{
    GLuint mainVAO;
    GL33::GBuffer gBuffer;

    ~RenderData()
    {
        glDeleteVertexArrays(1, &mainVAO); mainVAO = 0;
        // Other data will be destroyed by {`~GBuffer()`}
    }
};


GfxModule::GfxModule()
    : renderData_(nullptr), window_(nullptr)
{
}

#define glog (*core.g().log)

bool GfxModule::initGL(Core& core)
{
    ARES_log(glog, Trace, "Initializing OpenGL");

    window_->beginFrame(); // Make OpenGL context current on this thread

    int majorVersion = -1, minorVersion = -1;
    glGetIntegerv(GL_MAJOR_VERSION, &majorVersion);
    glGetIntegerv(GL_MINOR_VERSION, &minorVersion);

    if(majorVersion <= 0 || minorVersion <= 0)
    {
        ARES_log(glog, Error,
                 "Could not query OpenGL version, context is too old or broken!");
        return false;
    }

    { // Some debug logging
        ARES_log(glog, Debug,
                 "Got OpenGL %d.%d [%s, %s]",
                 majorVersion, minorVersion, glGetString(GL_VERSION), glGetString(GL_VENDOR));

        static constexpr const char* checkStrs[] = { "no", "yes" };
#define ARES_gfxLogHasGL(func) \
        ARES_log(glog, Trace, "Have %s? %s", #func, checkStrs[func != nullptr]);

        ARES_gfxLogHasGL(glMultiDrawElementsIndirect);

#undef ARES_gfxLogHasGL
    }

    return true;
}

bool GfxModule::initGBuffer(Core& core, Resolution resolution)
{
    ARES_log(glog, Trace, "Setting up G-Buffer");

    renderData_->gBuffer = GL33::GBuffer(resolution,
    {
        {GL_RGBA, GL_RGBA8}, // Albedo
        {GL_RGBA, GL_RGB10_A2}, // Normal
    });

    if(renderData_->gBuffer)
    {
        return true;
    }
    else
    {
        ARES_log(glog, Error,
                 "Failed to initialize G-Buffer (FBO status: %u)!",
                 glCheckFramebufferStatus(GL_FRAMEBUFFER));
        return false;
    }

    return true;
}

bool GfxModule::init(Core& core)
{
    renderData_ = new RenderData();

    window_ = core.g().facilities.get<Window>();
    if(!window_ || !window_->operator bool())
    {
        ARES_log(glog, Error,
                 "GfxModule requires a Window facility but %s",
                 window_ ? "it failed to initialize" : "it was not added");
        return false;
    }

    if(!initGL(core))
    {
        return false;
    }

    glGenVertexArrays(1, &renderData_->mainVAO);

    if(!initGBuffer(core, window_->resolution()))
    {
        return false;
    }

    return true;
}

void GfxModule::halt(Core& core)
{
    delete renderData_; renderData_ = nullptr; // (will destroy all OpenGL data)
    window_ = nullptr; // (will be destroyed by `Core`)
}

GfxModule::~GfxModule()
{
}


void GfxModule::mainUpdate(Core& core)
{
    // Poll events for the current and/or next frame[s]
    // TODO: Move input polling somewhere else so that even if the rendering is
    //       lagging rendering won't suffer
    window_->pollEvents();

    // Resize G-Buffer if required
    {
        auto windowResolution = window_->resolution();
        auto gBufferResolution = renderData_->gBuffer.resolution();
        if(windowResolution != gBufferResolution)
        {
            ARES_log(glog, Trace,
                     "Resizing G-Buffer: %s -> %s",
                     gBufferResolution, windowResolution);

            renderData_->gBuffer.resize(windowResolution);
            if(!renderData_->gBuffer)
            {
                ARES_log(glog, Error, "G-Buffer invalid after having been resized!");
            }
        }
    }

    // Execute rendering commands calculate for the previous frame
    // NOTE: *THIS IS ALWAYS ONE FRAME BEHIND!*
    //       Rendering commands for a frame are generated by worker threads by
    //       `updateTask()`, but `mainUpdate()` - that actually executes them -
    //       is run before `updateTask()`. This means that the rendering commands
    //       run will always be the ones generated for the previous frame,
    //       introducing a one-frame rendering lag
    window_->beginFrame();

    // FIXME IMPLEMENT: Run rendering commands for the previous frame here

    // FIXME TEST CODE - Remove
    auto resolution = window_->resolution();
    glViewport(0, 0, resolution.width, resolution.height);

    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, renderData_->gBuffer.fbo());
    glDisable(GL_FRAMEBUFFER_SRGB);
    glClearColor(0.2f, 0.4f, 0.6f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
    glEnable(GL_FRAMEBUFFER_SRGB);

    window_->endFrame();

    // FIXME TEST, USE A REAL EVENT SYSTEM TO TELL THE CORE TO QUIT!
    if(window_->quitRequested())
    {
        core.halt();
    }
}

Task GfxModule::updateTask(Core& core)
{
    auto updateFunc = [](TaskScheduler* scheduler, void* data)
    {
        // FIXME IMPLEMENT: Generate rendering commands for this frame here
    };
    return {updateFunc, this};
}

}
